### ISSUE TITLE
How to name this gem?

### ISSUE THREAD

**Issue by andrew2net** [metanorma/relaton-iso-bib#1]
@ronaldtse I've extracted the gem form `iso-bib-item`. So we have `relaton-bib` with `BibliographicItem` model implementation and `relaton-iso` with `IsoBibliographicItem` model implementation. But we have `isobib` gem which seems should be renamed to `realton-iso`. Do you have any idea how to name this gem?

**Comment by ronaldtse** [comment]
As discussed yesterday, I think relaton-iso should be renamed relaton-iso-bib and isobib should become relaton-iso. Thanks!
